server:
  applicationConnectors:
    - type: http
      port: 9902
  adminConnectors:
    - type: http
      port: 9802

commandListener:
  zookeeper: 127.0.0.1:9092

eventStore:
  zookeeper: 127.0.0.1:9092

eventPublisher:
  zookeeper: 127.0.0.1:9092
