server:
  applicationConnectors:
    - type: http
      port: 9901
  adminConnectors:
    - type: http
      port: 9801
  gzip:
    enabled: false

commandDispatcher:
  zookeeper: 127.0.0.1:9092

streamBroadcaster:
  zookeeper: 127.0.0.1:9092